src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AuthorRepository::class)]
class Author
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $username = null;

    #[ORM\Column(length: 150)]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    private ?int $nb_books = null;

    /**
     * @var Collection<int, Book>
     */
    #[ORM\OneToMany(targetEntity: Book::class, mappedBy: 'author')]
    private Collection $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getNbBooks(): ?int
    {
        return $this->nb_books;
    }

    public function setNbBooks(?int $nb_books): static
    {
        $this->nb_books = $nb_books;

        return $this;
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): static
    {
        if (!$this->books->contains($book)) {
            $this->books->add($book);
            $book->setAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): static
    {
        if ($this->books->removeElement($book)) {
            // set the owning side to null (unless already changed)
            if ($book->getAuthor() === $this) {
                $book->setAuthor(null);
            }
        }

        return $this;
    }

}

src/Form/AuthorType.php
<?php

namespace App\Form;

use App\Entity\Author;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class AuthorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username',TextType::class)
            ->add('email',TextType::class)
            ->add('nb_books',NumberType::class)
            ->add('save',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Author::class,
        ]);
    }
}

src/Controller/AuthorController.php
<?php

namespace App\Controller;

use App\Repository\AuthorRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Author;
use App\Form\AuthorType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;

final class AuthorController extends AbstractController
{
    #[Route('/author', name: 'app_author')]
    public function index(): Response
    {
        return $this->render('author/index.html.twig', [
            'controller_name' => 'AuthorController',
        ]);
    }

    #[Route('/showAuthor/{name}', name: 'app_showAuthor')]
    public function showAuthor($name): Response
    {
        return $this->render('author/show.html.twig', [
            'author_name' => $name,
        ]);
    }

    #[Route('/listAuthor', name: 'app_listAuthors')]
    public function listAuthor(): Response
    {
        $authors = array(
            array('id' => 1, 'picture' => '/images/VictorHugo.jpg', 'username' => 'Victor Hugo', 'email' => 'victor.hugo@gmail.com ', 'nb_books' => 100),
            array('id' => 2, 'picture' => '/images/william.jpg', 'username' => ' William Shakespeare', 'email' =>  ' william.shakespeare@gmail.com', 'nb_books' => 200),
            array('id' => 3, 'picture' => '/images/TahaHessin.jpg', 'username' => 'Taha Hussein', 'email' => 'taha.hussein@gmail.com', 'nb_books' => 300),
        );
        return $this->render('author/list.html.twig', [
            'authors' => $authors,
        ]);
    }

    #[Route('/detailsAuthor/{id}', name: 'app_detailsAuthors')]
    public function detailsAuthor($id)
    {
        $authors = array(
            array('id' => 1, 'picture' => '/images/VictorHugo.jpg', 'username' => 'Victor Hugo', 'email' => 'victor.hugo@gmail.com ', 'nb_books' => 100),
            array('id' => 2, 'picture' => '/images/william.jpg', 'username' => ' William Shakespeare', 'email' =>  ' william.shakespeare@gmail.com', 'nb_books' => 200),
            array('id' => 3, 'picture' => '/images/TahaHessin.jpg', 'username' => 'Taha Hussein', 'email' => 'taha.hussein@gmail.com', 'nb_books' => 300),
        );

        $author = null;
        foreach ($authors as $a) {
            if ($a['id'] == $id) {
                $author = $a;
            }
        }
        return $this->render('author/showAuthor.html.twig', [
            'author' => $author,
        ]);
    }

    //Find authors
    #[Route('/authors', name: 'author_getAuthors')]
    public function getAuthors(AuthorRepository $authRepo): Response
    {
        //$authors = $authRepo->findAll();
        $authors = $authRepo->findByEmail();
        return $this->render('author/list.html.twig', [
            'authors' => $authors,
        ]);
    }

    #[Route('/all', name: 'author_getAll')]
    public function getAll(ManagerRegistry $mr)
    {
        $manager = $mr->getManager();
        $authors = $manager->getRepository(Author::class)->findAll();
        return $this->render('author/list.html.twig', [
            'authors' => $authors,
        ]);
    }

    //add author static
    #[Route('/addAuthor', name: 'author_addAuthor')]
    public function addAuthor(EntityManagerInterface $mr): Response
    {
        $author = new Author();
        $author->setUsername("Abulkasem");
        $author->setEmail("abulkasem@gmail.com");
        $author->setNbBooks(150);
        if ($author) {
            $mr->persist($author);
            $mr->flush();
        }
        return $this->redirectToRoute("author_getAuthors");
    }

    //CRUD with form
    #[Route('/insert', name: 'author_insertAuthor')]
    public function insertAuthor(EntityManagerInterface $mr, Request $request)
    {
        $author = new Author();
        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $mr->persist($author);
            $mr->flush();
            return $this->redirectToRoute("author_getAuthors");
        }
        return $this->render('author/form.html.twig', [
            'authorForm' => $form,
        ]);
    }

    #[Route('/update/{id}', name: 'author_updateAuthor')]
    public function updateAuthor(EntityManagerInterface $mr, Request $request, $id): Response
    {
        $author = new Author();
        $author = $mr->getRepository(Author::class)->find($id);
        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $mr->persist($author);
            $mr->flush();
            return $this->redirectToRoute("author_getAuthors");
        }

        return $this->render('author/form.html.twig', [
            'authorForm' => $form,
        ]);
    }

    #[Route('/delete/{id}', name: "author_deleteAuthor")]
    public function deleteAuthor(EntityManagerInterface $mr, Request $request, $id): Response
    {
        $author = $mr->getRepository(Author::class)->find($id);
        $mr->remove($author);
        $mr->flush();
        return $this->redirectToRoute("author_getAuthors");
    }

    #[Route('/details/{id}', name: 'author_getAuthor')]
    public function getAuthor(AuthorRepository $authRepo, $id): Response
    {
        return $this->render('author/showAuthor.html.twig', [
            'auth' => $authRepo->find($id),
        ]);
    }

    #[Route('/authors/searchByBooks', name: 'author_search_by_books')]
    public function searchAuthorsByBooks(Request $request, AuthorRepository $authorRepo): Response
    {
        $min = $request->query->get('min');
        $max = $request->query->get('max');

        $authors = $authorRepo->findAuthorsByBookRange($min, $max);

        return $this->render('author/searchByBooks.html.twig', [
            'authors' => $authors,
        ]);
    }

    #[Route('/authors/deleteEmpty', name: 'author_delete_empty')]
    public function deleteAuthorsWithNoBooks(AuthorRepository $authorRepo): Response
    {
        $deletedCount = $authorRepo->deleteAuthorsWithNoBooks();

        return $this->render('author/deleteEmptyResult.html.twig', [
            'count' => $deletedCount,
        ]);
    }
}

templates/author/deleteEmptyResult.html.twig
<h2>Suppression des auteurs sans livres</h2>
<p>{{ count }} auteur(s) ont été supprimés.</p>

templates/author/form.html.twig
{{form(authorForm)}}

templates/author/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AuthorController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/Users/DELL/Desktop/FirstApp/src/Controller/AuthorController.php</code></li>
        <li>Your template at <code>C:/Users/DELL/Desktop/FirstApp/templates/author/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/author/list.html.twig
<h1>Le tableau comporte
	{{authors | length}}
	auteurs
</h1>

{% if authors is empty or authors is not defined %}
	<h2>Verifier votre tableau</h2>
{% else %}
	<a href="{{ path('author_insertAuthor')}}">Ajouter un nouveau auteur</a>
	<table border="1">
		<tr>
			<th>Identifiant</th>
			<th>Auteur</th>
			<th>Email de l'auteur</th>
			{# <th>Photo</th> #}
			<th>Nombre de livre</th>
			<th colspan="3">Actions</th>
			
		</tr>
		{% set l=0 %}
		{% for author in authors %}
			<tr>
				<td>{{author.id }}</td>
				<td>{{author.username | upper}}</td>
				<td>{{author.email}}</td>
				{# <td><img src="{{author.picture}}" width="150"></td> #}
				<td>{{author.nbBooks}}
					Livres</td>
				{% set l=l+author.nbBooks %}
				<td>
					<a href="{{path('author_getAuthor', {'id': author.id })}}">Details</a>
				</td>
				<td>
					<a href="{{path('author_updateAuthor', {'id': author.id })}}">Edit</a>
				</td>
				<td>
					<a href="{{path('author_deleteAuthor', {'id': author.id })}}">Delete</a>
				</td>
			</tr>
		{% endfor %}
	</table>
	<h1>Le nombre de livres de tous les auteurs=
		{{l}}
	</h1>
{% endif %}

templates/author/searchByBooks.html.twig
<h1>Rechercher l'auteur par nombre de livres </h1>

<form method="get" action="{{ path('author_search_by_books') }}">
	<input type="number" name="min" placeholder="Min livres">
	<input type="number" name="max" placeholder="Max livres">
	<button type="submit">Search</button>
</form>

{% if authors is not empty %}
	<table border="1">
		<tr>
			<th>Nom</th>
			<th>Nombre de livres</th>
		</tr>
		{% for a in authors %}
			<tr>
				<td>{{ a.username }}</td>
				<td>{{ a.nbBooks }}</td>
			</tr>
		{% endfor %}
	</table>
{% endif %}

templates/author/show.html.twig
{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ author_name }}</h1>
</div>
{% endblock %}

templates/author/showAuthor.html.twig
<h1>Details de l'auteur</h1>
<h3>Nom: {{auth.username}}</h3>
<h3>Email: {{auth.email}}</h3>
<h3>Nombre de livre: {{auth.nbBooks}} </h3>
{# <img src="{{auth.picture}}" width="150"> #}